# Generated by Django 6.0.7 on 2026-07-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
