# Generated by Django 6.0.7 on 2026-07-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
