# Generated by Django 6.0.7 on 2026-07-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
